"use client";
import { useState } from "react";
import { signIn } from "next-auth/react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { Suspense } from "react";

function AuthInner(){
 const params=useSearchParams(); const [mode,setMode]=useState(params.get("mode")==="signup"?"signup":"login");
 const [role,setRole]=useState<"athlete"|"coach">("athlete"); const [name,setName]=useState(""); const [dob,setDob]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError(null);try{if(mode==="signup"){const r=await fetch("/api/auth/signup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,password,role,dateOfBirth:dob})});const d=await r.json();if(!r.ok) throw new Error(d.error||"Signup failed");}const result=await signIn('credentials',{email,password,redirect:false});if(!result||result.error) throw new Error('Email or password is incorrect.');const session=await fetch('/api/auth/session').then(r=>r.json());const actual=session?.user?.role;const next=params.get('next');if(mode==='login'&&next&&next.startsWith('/')&&!next.startsWith('//')){window.location.href=next;return}window.location.href=actual==='admin'?'/admin':actual==='coach'?(mode==='signup'?'/coach/onboarding':'/coach'):(mode==='signup'?'/app/onboarding':'/app');}catch(err){setError(err instanceof Error?err.message:"Authentication failed.");}finally{setBusy(false)}};
 const google=async()=>{setBusy(true);setError(null);try{if(mode==='signup'&&role==='coach'){setError('Coach accounts using Google must sign in with an existing coach account or use email/password to create a new coach account.');setBusy(false);return}await signIn('google',{callbackUrl:'/auth/complete'});}catch{setError("Google sign-in is not configured on this deployment.");setBusy(false)}};
 return <div className="page"><div className="mobile" style={{padding:"34px 0"}}><Link href="/" className="small muted">← Kotaana</Link><div className="card" style={{marginTop:22}}><h1 style={{margin:"0 0 6px",fontSize:27}}>{mode==="signup"?"Create your account":"Welcome back"}</h1><p className="subtitle">{mode==="signup"?"Choose Athlete or Coach. Admin access is never a public role option.":"Your account role is read from your authenticated account."}</p><form className="stack" style={{marginTop:18}} onSubmit={submit}>{mode==="signup"&&<><div><label className="label">Full name</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></div><div><label className="label">Role</label><div className="checkboxRow"><label className="check"><input type="radio" checked={role==="athlete"} onChange={()=>setRole("athlete")}/> Athlete</label><label className="check"><input type="radio" checked={role==="coach"} onChange={()=>setRole("coach")}/> Coach / Gym</label></div></div></>}{mode==="signup"&&<div><label className="label">Date of birth</label><input className="input" type="date" value={dob} onChange={e=>setDob(e.target.value)} required/></div>}<div><label className="label">Email</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div><label className="label">Password</label><input className="input" type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></div>{error&&<div className="danger small">{error}</div>}<button className="btn primary" disabled={busy}>{busy?"Working…":mode==="signup"?"Create account":"Log in"}</button></form><div style={{margin:"14px 0",borderTop:"1px solid var(--border)"}}/><button className="btn secondary" style={{width:"100%"}} disabled={busy} onClick={google}>Continue with Google</button><div className="row" style={{justifyContent:"space-between",marginTop:16}}><Link className="small muted" href="/auth/forgot">Forgot password?</Link><span></span></div><div className="row" style={{justifyContent:"center",marginTop:10}}><span className="small muted">{mode==="signup"?"Already have an account?":"Need an account?"}</span><button className="btn secondary small" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Log in":"Sign up"}</button></div><p className="small dim" style={{marginTop:14}}>By continuing you agree to <Link href="/terms" className="muted">Terms</Link> and <Link href="/privacy" className="muted">Privacy</Link>.</p></div></div></div>
}
export default function AuthPage(){return <Suspense fallback={<div className="page"><div className="mobile" style={{padding:40}}>Loading…</div></div>}><AuthInner/></Suspense>}
