"use client";
import { useEffect, useState } from "react";
import LocationButton from "../LocationButton";
const styles=["vegetarian","vegan","high_protein","low_carb"];const allergies=["dairy","nuts","gluten","egg","soy","fish_shellfish"];

/** Nutrition inputs. Shared by Settings and the Nutrition page so both edit the same profile fields. */
export default function NutritionPrefsForm({onSaved}:{onSaved?:(profile:any)=>void}){
 const [profile,setProfile]=useState<any>(null);const [busy,setBusy]=useState(false);const [msg,setMsg]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/profile").then(r=>r.json()).then(d=>setProfile(d.profile))},[]);
 const save=async()=>{setBusy(true);setMsg(null);const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({dietaryStyle:profile.dietaryStyle,allergies:profile.allergies,targetCalories:profile.targetCalories})});const d=await r.json();setBusy(false);if(!r.ok){setMsg(d.error||"Could not save");return}setProfile(d.profile);setMsg("Nutrition preferences saved.");onSaved?.(d.profile)};
 if(!profile)return <p className="subtitle">Loading preferences…</p>;
 return <div><div className="grid grid2" style={{marginTop:12}}><div><label className="label">Daily calorie target</label><input className="input" type="number" min="1200" max="6000" value={profile.targetCalories||2200} onChange={e=>setProfile({...profile,targetCalories:Number(e.target.value)})}/></div><div><label className="label">Location</label><div className="item"><span>{profile.locationCity?[profile.locationCity,profile.locationCountry].filter(Boolean).join(", "):(profile.locationLat!=null?"Saved":"Not set")}</span><LocationButton label={profile.locationCity?"Update":"Use my location"} className="btn secondary small" onDone={()=>fetch("/api/profile").then(r=>r.json()).then(d=>setProfile(d.profile))}/></div></div></div><label className="label" style={{marginTop:14}}>Diet style</label><div className="checkboxRow">{styles.map(x=><label className="check" key={x}><input type="checkbox" checked={(profile.dietaryStyle||[]).includes(x)} onChange={e=>setProfile({...profile,dietaryStyle:e.target.checked?[...new Set([...(profile.dietaryStyle||[]),x])]:profile.dietaryStyle.filter((v:string)=>v!==x)})}/>{x.replace('_',' ')}</label>)}</div><label className="label" style={{marginTop:14}}>Allergies / foods to avoid</label><div className="checkboxRow">{allergies.map(x=><label className="check" key={x}><input type="checkbox" checked={(profile.allergies||[]).includes(x)} onChange={e=>setProfile({...profile,allergies:e.target.checked?[...new Set([...(profile.allergies||[]),x])]:profile.allergies.filter((v:string)=>v!==x)})}/>{x.replace('_',' ')}</label>)}</div><button className="btn primary" style={{marginTop:14}} onClick={save} disabled={busy}>{busy?'Saving…':'Save preferences & refresh'}</button>{msg&&<p className="small muted" style={{marginTop:8}}>{msg}</p>}</div>}
