"use client";

export type TrackPoint = { lat:number; lng:number; t:number; accuracy?:number; speed?:number|null; altitude?:number|null };
export type TrackDraft = { activityType:"run"|"walk"|"ride"; startedAt:number; points:TrackPoint[] };
const DB_NAME="kotaana-track", STORE="drafts", KEY="active", FALLBACK_KEY="kotaana.track.active";
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{if(typeof indexedDB==="undefined")return reject(new Error("IndexedDB unavailable"));const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error("Could not open track storage"));});}
export async function saveTrackDraft(draft:TrackDraft){if(typeof window==="undefined")return;try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(draft,KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error("Could not save track draft"));});db.close();}catch{try{localStorage.setItem(FALLBACK_KEY,JSON.stringify(draft));}catch{}}}
export async function loadTrackDraft():Promise<TrackDraft|null>{if(typeof window==="undefined")return null;try{const db=await openDb();const v=await new Promise<TrackDraft|null>((resolve,reject)=>{const tx=db.transaction(STORE,"readonly"),r=tx.objectStore(STORE).get(KEY);r.onsuccess=()=>resolve((r.result as TrackDraft|undefined)??null);r.onerror=()=>reject(r.error||new Error("Could not load track draft"));});db.close();return v;}catch{try{const raw=localStorage.getItem(FALLBACK_KEY);return raw?JSON.parse(raw) as TrackDraft:null;}catch{return null;}}}
export async function clearTrackDraft(){if(typeof window==="undefined")return;try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).delete(KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error||new Error("Could not clear track draft"));});db.close();}catch{}try{localStorage.removeItem(FALLBACK_KEY);}catch{}}
