import { NextResponse } from "next/server";import { z } from "zod";import { prisma } from "@/lib/db/prisma";import { apiAuth } from "@/lib/auth/guard";
const schema=z.object({planId:z.string().optional(),exerciseId:z.string(),exerciseName:z.string().optional(),setsDone:z.number().int().min(0).max(50).optional(),repsDone:z.string().max(50).optional(),durationSec:z.number().int().min(0).max(7200).optional(),effort:z.enum(["easy","ok","hard"]),completed:z.boolean().default(true),notes:z.string().max(500).optional()});
function dateOnly(){const n=new Date();return new Date(Date.UTC(n.getUTCFullYear(),n.getUTCMonth(),n.getUTCDate()));}
export async function POST(req:Request){
 const a=await apiAuth("athlete");if("error"in a)return a.error;const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:"Invalid performance data",details:p.error.flatten()},{status:400});const today=dateOnly();
 const plan=await prisma.workoutPlan.findFirst({where:{id:p.data.planId||undefined,userId:a.session.user.id,date:today,isActive:true},orderBy:{createdAt:"desc"}});
 if(!plan)return NextResponse.json({error:"Active workout plan not found."},{status:404});const planData=plan.planData as any;const moves=Array.isArray(planData?.moves)?planData.moves:[];const move=moves.find((m:any)=>m.exerciseId===p.data.exerciseId&&m.role!=="hydration");if(!move)return NextResponse.json({error:"Exercise is not part of the active workout."},{status:400});
 const row=await prisma.exercisePerformance.create({data:{userId:a.session.user.id,date:today,exerciseId:p.data.exerciseId,exerciseName:p.data.exerciseName||move.name,setsDone:p.data.setsDone,repsDone:p.data.repsDone,durationSec:p.data.durationSec,effort:p.data.effort,completed:p.data.completed,notes:p.data.notes}});
 const prior=Array.isArray(plan.completedExercises)?plan.completedExercises.map(String):[];const next=p.data.completed&&!prior.includes(p.data.exerciseId)?[...prior,p.data.exerciseId]:prior;const actionable=moves.filter((m:any)=>m.role!=="hydration").length;const completionRate=actionable?Math.min(1,next.length/actionable):0;
 await prisma.$transaction([prisma.workoutPlan.update({where:{id:plan.id},data:{completedExercises:next}}),prisma.workoutLog.upsert({where:{userId_date:{userId:a.session.user.id,date:today}},create:{userId:a.session.user.id,date:today,planId:plan.id,completionRate},update:{planId:plan.id,completionRate,notes:p.data.notes}}),prisma.profile.update({where:{userId:a.session.user.id},data:{lastActiveAt:new Date()}})]);
 return NextResponse.json({ok:true,performance:row,completionRate});
}
