"use client";
import {useState} from 'react';
export default function CoachFinder(){
 const [q,setQ]=useState('');const [results,setResults]=useState<any[]>([]);const [msg,setMsg]=useState('');const [selectedCoach,setSelectedCoach]=useState<any>(null);const [pay,setPay]=useState<any>({amount:10000,number:'',name:''});
 const search=async()=>{const r=await fetch('/api/connections/search?q='+encodeURIComponent(q));const d=await r.json();if(r.ok)setResults(d.results||[]);else setMsg(d.error)};
 const request=async(id:string)=>{const r=await fetch('/api/connections/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({coachId:id})});const d=await r.json();setMsg(r.ok?(d.message||'Request sent — the coach will see it in their roster.'):d.error)};
 const payNow=async()=>{if(!selectedCoach){setMsg('Select a coach first.');return}const r=await fetch('/api/payments/momo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount:Number(pay.amount),payerNumber:pay.number,payerName:pay.name,planType:'coach_service',coachId:selectedCoach.id,idempotencyKey:crypto.randomUUID()})});const d=await r.json();setMsg(r.ok?(d.message||'Payment request created.'):d.error)};
 return <div className="stack"><div><span className="pill orange">COACH</span><h1 style={{fontSize:28,margin:'9px 0 4px'}}>Find a coach</h1><p className="subtitle">Search by name, email or published MoMo details.</p></div><div className="card"><div className="row"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Coach name or email"/><button className="btn primary" onClick={search}>Search</button></div>{msg&&<p className="small muted">{msg}</p>}</div><div className="list">{results.map(c=><div className="item" key={c.id}><div><strong>{c.name||c.email}</strong><div className="small muted">{c.momoName||'MoMo not published'} · {c.momoNumber||'No number'}</div></div><button className="btn secondary" onClick={()=>{setSelectedCoach(c);request(c.id)}}>{selectedCoach?.id===c.id?'Selected':'Request'}</button></div>)}{!results.length&&<div className="empty">Search to find coaches.</div>}</div><div className="card"><h2 className="sectionTitle">MoMo payment</h2><p className="subtitle">Select a coach first. The payment is attached to that coach for coach-side approval and uses the coach MoMo number when one is published.</p>{selectedCoach&&<p className="small muted" style={{marginTop:8}}>Selected: <strong>{selectedCoach.name||selectedCoach.email}</strong>{selectedCoach.momoNumber?` · ${selectedCoach.momoNumber}`:''}</p>}<div className="grid grid2" style={{marginTop:12}}><input className="input" type="number" min="100" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})} placeholder="Amount RWF"/><input className="input" value={pay.number} onChange={e=>setPay({...pay,number:e.target.value})} placeholder="Your MoMo number"/><input className="input" value={pay.name} onChange={e=>setPay({...pay,name:e.target.value})} placeholder="MoMo account name"/></div><button className="btn primary" style={{marginTop:12}} onClick={payNow}>Start MoMo payment</button></div></div>
}
