"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {clearTrackDraft,loadTrackDraft,saveTrackDraft,type TrackPoint} from "@/lib/track/session-store";
type Activity="run"|"walk"|"ride";
const labels:Record<Activity,string>={run:"Run",walk:"Walk",ride:"Ride"};
export default function TrackScreen(){
 const [activityType,setActivityType]=useState<Activity>("run"),[running,setRunning]=useState(false),[resumed,setResumed]=useState(false),[points,setPoints]=useState<TrackPoint[]>([]),[message,setMessage]=useState(""),[distance,setDistance]=useState(0),[duration,setDuration]=useState(0),[screenState,setScreenState]=useState<"visible"|"background">("visible");
 const watch=useRef<number|null>(null),started=useRef(0),lastPoint=useRef<TrackPoint|null>(null),pointsRef=useRef<TrackPoint[]>([]),activityRef=useRef<Activity>("run"),runningRef=useRef(false);
 const updatePoints=useCallback((next:TrackPoint[])=>{pointsRef.current=next;setPoints(next);setDistance(haversineTotal(next));},[]);
 const persistDraft=useCallback(async(next=pointsRef.current)=>{if(!runningRef.current||!started.current||!next.length)return;await saveTrackDraft({activityType:activityRef.current,startedAt:started.current,points:next});},[]);
 const clearWatcher=useCallback(()=>{if(watch.current!=null&&navigator.geolocation){navigator.geolocation.clearWatch(watch.current);watch.current=null;}},[]);
 const handlePoint=useCallback((position:GeolocationPosition)=>{const c=position.coords,p:TrackPoint={lat:c.latitude,lng:c.longitude,t:position.timestamp||Date.now(),accuracy:c.accuracy,speed:c.speed,altitude:c.altitude};if(p.accuracy!=null&&p.accuracy>250){setMessage(`GPS accuracy is ${Math.round(p.accuracy)} m. Waiting for a better fix…`);return;}const prev=lastPoint.current;if(prev&&p.t<=prev.t)return;if(prev){const km=haversine(prev,p),hours=(p.t-prev.t)/3600000;if(hours>0&&km/hours>maxSpeed(activityRef.current))return;}lastPoint.current=p;const next=[...pointsRef.current,p].slice(-10000);updatePoints(next);void persistDraft(next);},[persistDraft,updatePoints]);
 const startWatcher=useCallback(()=>{if(!navigator.geolocation||!runningRef.current)return;clearWatcher();watch.current=navigator.geolocation.watchPosition(handlePoint,e=>{if(e.code===1)setMessage("Location permission is required. Re-enable location permission to continue tracking.");else if(e.code===2)setMessage("GPS signal is temporarily unavailable. Kotaana will keep trying.");else if(e.code===3)setMessage("GPS fix is taking longer than expected. Kotaana will keep trying.");else setMessage(e.message||"GPS tracking error. Kotaana will keep trying.");},{enableHighAccuracy:true,maximumAge:3000,timeout:3000});},[clearWatcher,handlePoint]);
 useEffect(()=>{let mounted=true;void loadTrackDraft().then(d=>{if(!mounted||!d||!d.points.length)return;activityRef.current=d.activityType;setActivityType(d.activityType);started.current=d.startedAt;pointsRef.current=d.points;lastPoint.current=d.points[d.points.length-1]??null;setPoints(d.points);setDistance(haversineTotal(d.points));setDuration(Math.max(0,Math.floor((Date.now()-d.startedAt)/1000)));setRunning(true);runningRef.current=true;setResumed(true);setMessage("Unfinished tracking session restored. GPS will continue when the phone provides a new fix.");setTimeout(startWatcher,0);});return()=>{mounted=false;};},[startWatcher]);
 useEffect(()=>{const onVisibility=()=>{const bg=document.visibilityState!=="visible";setScreenState(bg?"background":"visible");if(runningRef.current){if(!bg){startWatcher();setMessage("GPS tracking resumed. Checking for a fresh location fix…");}void persistDraft();}};document.addEventListener("visibilitychange",onVisibility);return()=>document.removeEventListener("visibilitychange",onVisibility);},[persistDraft,startWatcher]);
 useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>{if(started.current)setDuration(Math.max(0,Math.floor((Date.now()-started.current)/1000)));},1000);return()=>window.clearInterval(timer);},[running]);
 useEffect(()=>()=>clearWatcher(),[clearWatcher]);
 const start=()=>{if(!navigator.geolocation){setMessage("This device does not provide GPS location.");return;}setMessage("Requesting GPS permission and waiting for a good fix…");navigator.geolocation.getCurrentPosition(position=>{const c=position.coords,initial:TrackPoint={lat:c.latitude,lng:c.longitude,t:position.timestamp||Date.now(),accuracy:c.accuracy,speed:c.speed,altitude:c.altitude};if(initial.accuracy!=null&&initial.accuracy>250){setMessage(`GPS accuracy is ${Math.round(initial.accuracy)} m. Move outdoors and wait for a better fix.`);return;}const startedAt=Date.now();activityRef.current=activityType;started.current=startedAt;lastPoint.current=initial;runningRef.current=true;setRunning(true);setResumed(false);updatePoints([initial]);void saveTrackDraft({activityType,startedAt,points:[initial]});startWatcher();setMessage(`${labels[activityType]} tracking is active. You can lock the screen; the native app can continue GPS in the background.`);},e=>setMessage(e.code===3?"GPS fix timed out. Keep location enabled and try again.":`Location is required: ${e.message}`),{enableHighAccuracy:true,timeout:3000,maximumAge:0});};
 const stop=async()=>{const finalPoints=pointsRef.current;setRunning(false);runningRef.current=false;clearWatcher();const finalDuration=started.current?Math.max(1,Math.floor((Date.now()-started.current)/1000)):duration,dist=haversineTotal(finalPoints);setDuration(finalDuration);setDistance(dist);if(finalPoints.length<2||dist<0.01){setMessage("Move a little longer so Kotaana can record a route.");return;}const r=await fetch('/api/track/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({activityType:activityRef.current,distanceKm:dist,durationSec:finalDuration,path:finalPoints})}),d=await r.json().catch(()=>({}));if(r.ok){await clearTrackDraft();setResumed(false);setMessage(`${labels[activityRef.current]} saved successfully.`);}else{runningRef.current=true;setRunning(true);setMessage(d.error||"Could not save the route. Your tracking session remains stored on this device; try again when online.");}};
 const discard=async()=>{runningRef.current=false;setRunning(false);clearWatcher();await clearTrackDraft();pointsRef.current=[];lastPoint.current=null;setPoints([]);setDistance(0);setDuration(0);setResumed(false);setMessage("Tracking session discarded.");};
 return <div className="stack"><div><span className="pill orange">TRACK ME</span><h1 style={{fontSize:28,margin:'9px 0 4px'}}>Track your session</h1><p className="subtitle">GPS tracking recovers after the screen is locked, the browser is resumed, or the page is reloaded. A fully powered-off phone cannot collect GPS points while it has no power.</p></div><div className="card"><div className="checkboxRow" style={{marginBottom:14}}>{(Object.keys(labels) as Activity[]).map(type=><button key={type} className={`btn ${activityType===type?'primary':'secondary'}`} onClick={()=>{if(!running){activityRef.current=type;setActivityType(type);}}} disabled={running}>{labels[type]}</button>)}</div><div className="grid grid3"><div><div className="small muted">Status</div><div className="metric" style={{fontSize:22}}>{running?(screenState==="background"?"Background":"Live"):"Ready"}</div></div><div><div className="small muted">Distance</div><div className="metric" style={{fontSize:22}}>{distance.toFixed(2)} km</div></div><div><div className="small muted">Time</div><div className="metric" style={{fontSize:22}}>{Math.floor(duration/60)}:{String(duration%60).padStart(2,'0')}</div></div></div>{resumed&&<p className="small" style={{marginTop:10}}>Recovered session: the route is stored locally while tracking is active, so a reload/network interruption does not immediately lose it.</p>}{message&&<p className="small muted">{message}</p>}{!running?<button className="btn primary" style={{width:'100%',marginTop:12}} onClick={start}>{resumed?'Resume GPS tracking':`Enable location & start ${labels[activityType].toLowerCase()}`}</button>:<div className="row" style={{marginTop:12}}><button className="btn" style={{flex:1}} onClick={stop}>Stop & save</button><button className="btn secondary" onClick={discard}>Discard</button></div>}<p className="small dim">For Android background/locked-screen tracking, the installed native Android build must use a foreground location service and show its persistent tracking notification. The browser version keeps the watcher alive and restores it when the browser resumes.</p></div></div>;
}
function maxSpeed(a:Activity){return a==="walk"?15:a==="ride"?120:45;}
function haversine(a:TrackPoint,b:TrackPoint){const R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function haversineTotal(a:TrackPoint[]){let total=0;for(let i=1;i<a.length;i++)total+=haversine(a[i-1],a[i]);return total;}
