import type { ExerciseRow, PerformanceRecord, SessionMove, UserWorkoutContext, BuiltSession } from "./types";
import { NoSafeExerciseError } from "./types";
export { NoSafeExerciseError };
import { activeRules, capEffort, effortCap } from "@/lib/health/conditions";

const DEFAULTS = { level: "beginner", track: "general", goal: "general_fitness", availableMinutes: 35, equipment: ["bodyweight"] };
const RANK: Record<string, number> = { beginner: 1, intermediate: 2, advanced: 3 };
const norm = (s: unknown) => String(s ?? "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const hasAny = (text: string, terms: string[]) => terms.some(t => text.includes(norm(t)));
const todayKey = (d = new Date()) => d.toISOString().slice(0, 10);
function hashSeed(userId: string, dateKey: string) { let h = 2166136261; for (const ch of `${userId}:${dateKey}`) h = Math.imul(h ^ ch.charCodeAt(0), 16777619); return h >>> 0; }
function tags(e: ExerciseRow) { return norm([e.name,e.bodyPart,e.target,e.category,e.muscleGroup,...(e.secondaryMuscles??[]),...(e.roleTags??[]),e.movementPattern].join(" ")); }
function isStretch(e: ExerciseRow){const t=tags(e);return (e.roleTags??[]).includes("stretch")||hasAny(t,["stretch","mobility","flexibility","joint rotation","child pose","cat cow","90 90"])}
function isWarmup(e: ExerciseRow){const t=tags(e);return (e.roleTags??[]).includes("warmup")||hasAny(t,["warm up","dynamic","march","jog","jumping jack","arm circle","leg swing","mobilization"])}
function isCore(e: ExerciseRow){const t=tags(e);return (e.roleTags??[]).includes("core")||hasAny(t,["core","abdominal","abs","plank","dead bug","bird dog","oblique"])}
function isOutdoor(e: ExerciseRow){const t=tags(e);return (e.roleTags??[]).includes("outdoor")||hasAny(t,["run","jog","walk","hike","sprint","hill","outdoor"])}
function isStrengthLike(e: ExerciseRow){return hasAny(tags(e),["squat","lunge","hinge","deadlift","press","push","pull","row","carry","calf","curl","extension"])}
function muscleKeys(e: ExerciseRow){return [e.muscleGroup,e.target,...(e.secondaryMuscles??[])].filter(Boolean).map(norm)}
function equipmentOk(e: ExerciseRow, have: string[], excluded: string[]){const eq=norm(e.equipment||"bodyweight");if(excluded.some(x=>eq.includes(norm(x))))return false;if(!e.equipment||hasAny(eq,["body only","bodyweight","body only no equipment","none","no equipment"]))return true;if(!have.length)return hasAny(eq,["bodyweight","body only","none"]);return have.map(norm).some(h=>eq.includes(h)||h.includes(eq));}
function difficultyOk(e: ExerciseRow, level: string){const required=RANK[norm(e.difficulty||"beginner")]||1;const actual=RANK[norm(level)]||1;return required<=actual+1;}
function ageOk(e: ExerciseRow, ageBand: string|null){if(!ageBand||ageBand==="unknown")return !(e.safetyTags??[]).some(x=>["age_restricted","high_risk"].includes(norm(x)));if(ageBand.startsWith("youth"))return !(e.safetyTags??[]).some(x=>["adult_only","high_risk"].includes(norm(x)));return true;}
function injurySafe(e: ExerciseRow, ctx: UserWorkoutContext){
  const unknown=ctx.injuryDataKnown===false; const t=`${tags(e)} ${norm(e.instructions)}`; const contraindications=new Set((e.contraindicationTags??[]).map(norm));
  if(unknown)return !(e.safetyTags??[]).some(x=>["high_risk","injury_sensitive","advanced_load"].includes(norm(x)));
  for(const raw of ctx.injuries??[]){const i=norm(typeof raw==="string"?raw:`${raw.bodyPart??""} ${raw.restrictions??""}`);if(!i)continue;
    const mappings:[RegExp,string[],string[]][]=[[/knee/, ["knee","squat_depth","impact"],["jump","pistol","deep squat","lunge jump","box jump"]],[/shoulder|rotator/, ["shoulder","overhead"],["overhead press","snatch","handstand","dip","muscle up"]],[/lower back|lumbar|back/, ["lower back","lower_back","hinge"],["good morning","heavy deadlift","sit up","hanging leg raise"]],[/wrist/, ["wrist","loaded wrist"],["handstand","planche","push up"]],[/ankle/, ["ankle","impact"],["jump","sprint","box jump"]]];
    for(const [rx,cts,names] of mappings)if(rx.test(i)&&(cts.some(x=>contraindications.has(norm(x)))||hasAny(t,names)))return false;
  }
  if(ctx.otherLimitations&&hasAny(norm(ctx.otherLimitations),["no jumping","no running","no impact"])&&hasAny(t,["jump","run","sprint","impact"]))return false;
  return true;
}
function performanceAdjustment(p?: PerformanceRecord){if(!p)return {setsDelta:0,repsDelta:0,effort:"moderate" as const};if(!p.completed||p.effort==="hard")return {setsDelta:-1,repsDelta:-2,effort:"moderate" as const};if(p.effort==="easy")return {setsDelta:0,repsDelta:2,effort:"hard" as const};return {setsDelta:0,repsDelta:0,effort:"moderate" as const};}
function scoreExercise(e: ExerciseRow, ctx:{level:string;goal:string;track:string;recentIds:Set<string>;recentMuscles:Set<string>;recentPatterns:Set<string>;weeklyMuscles:Set<string>;weeklyPatterns:Set<string>;seed:number;history:PerformanceRecord[];readiness:number;aiPreferred:Set<string>;blocked:Set<string>}){
  let score=100; const n=tags(e); const diff=norm(e.difficulty||"beginner"); const muscles=muscleKeys(e); const pattern=norm(e.movementPattern);
  if(ctx.blocked.has(e.id))return -Infinity; if(ctx.recentIds.has(e.id))score-=48;if(ctx.recentMuscles.size&&muscles.some(m=>ctx.recentMuscles.has(m)))score-=16;if(ctx.weeklyMuscles.size&&muscles.some(m=>ctx.weeklyMuscles.has(m)))score-=10;if(pattern&&ctx.recentPatterns.has(pattern))score-=12;if(pattern&&ctx.weeklyPatterns.has(pattern))score-=8;
  if(ctx.aiPreferred.has(e.id))score+=18;if(ctx.track!=="general"&&(e.tracks??[]).some(t=>norm(t)===norm(ctx.track)))score+=16;if(ctx.goal!=="general_fitness"&&(e.goals??[]).some(g=>norm(g)===norm(ctx.goal)))score+=14;
  score+=Math.max(0,10-Math.abs((RANK[diff]||1)-(RANK[ctx.level]||1))*7);
  if(/fat|weight/.test(ctx.goal)&&hasAny(n,["burpee","mountain climber","cardio","walk","run"]))score+=6;if(/muscle|hypertrophy/.test(ctx.goal)&&isStrengthLike(e))score+=8;
  if(ctx.readiness<45&&hasAny(n,["mobility","stretch","walk","low impact","bodyweight"]))score+=12;if(ctx.readiness<35&&isStrengthLike(e))score-=15;
  const perf=ctx.history.filter(p=>p.exerciseId===e.id).sort((a,b)=>b.date.localeCompare(a.date))[0];if(perf)score+=perf.completed&&perf.effort==="easy"?8:perf.effort==="hard"?-6:-1;
  return score+((ctx.seed ^ e.id.length*97)%13);
}
function choose<T>(arr:T[],count:number,seed:number){return [...arr].sort((a,b)=>((seed+JSON.stringify(a).length*31)%997)-((seed+JSON.stringify(b).length*31)%997)).slice(0,count);}
function prescription(role:SessionMove["role"],level:string,perf?:PerformanceRecord,readiness=70){const r=RANK[level]||1;if(role==="stretch")return{durationSec:45,restSec:10,effort:"easy" as const,estimatedMin:1};if(role==="warmup"||role==="cooldown")return{durationSec:60,restSec:15,effort:"easy" as const,estimatedMin:1};if(role==="hydration")return{estimatedMin:1,effort:"easy" as const};if(role==="outdoor")return{durationSec:r>=2?900:600,effort:readiness<45?"easy" as const:"moderate" as const,estimatedMin:r>=2?15:10};if(role==="core")return{sets:r>=2?3:2,durationSec:readiness<45?25:r>=2?35:25,restSec:30,effort:readiness<45?"easy" as const:"moderate" as const,estimatedMin:3};let sets=r>=3?4:3,reps:number|string=r===1?10:r===2?12:"8-12";const adj=performanceAdjustment(perf);sets=Math.max(2,sets+adj.setsDelta);reps=typeof reps==="number"?Math.max(6,reps+adj.repsDelta):reps;let effort: "easy"|"moderate"|"hard"=adj.effort;if(readiness<35){sets=Math.max(2,sets-1);effort="easy";}return{sets,reps,restSec:60,effort,estimatedMin:5};}

export function buildDailySession(exercises:ExerciseRow[],rawCtx:UserWorkoutContext,date=new Date()):BuiltSession{
  const usedDefaults:string[]=[];const level=rawCtx.level||(usedDefaults.push("level"),DEFAULTS.level);const track=rawCtx.track||(usedDefaults.push("track"),DEFAULTS.track);const goal=rawCtx.goal||(usedDefaults.push("goal"),DEFAULTS.goal);const minutes=rawCtx.availableMinutes||(usedDefaults.push("availableMinutes"),DEFAULTS.availableMinutes);const have=rawCtx.equipment?.length?rawCtx.equipment:(usedDefaults.push("equipment"),DEFAULTS.equipment);const dateKey=todayKey(date),seed=hashSeed(rawCtx.userId,dateKey),highStress=(rawCtx.stressLevel??0)>=4,readiness=Math.max(0,(rawCtx.readiness??70)-(highStress?10:0));
  const rules=activeRules(rawCtx.conditions,rawCtx.isPregnant),conditionAvoid=rules.flatMap(r=>r.avoidExercises??[]),cap=effortCap(rules);
  const healthNotes=[...rules.map(r=>r.workoutNote).filter(Boolean) as string[],...(highStress?["High stress reported: today's intensity is reduced slightly."]:[])];
  const recentIds=new Set(rawCtx.recentExerciseIds??[]),recentMuscles=new Set((rawCtx.recentMuscleTags??[]).map(norm)),recentPatterns=new Set((rawCtx.recentMovementPatterns??[]).map(norm)),weeklyMuscles=new Set((rawCtx.weeklyMuscleTags??[]).map(norm)),weeklyPatterns=new Set((rawCtx.weeklyMovementPatterns??[]).map(norm)),history=rawCtx.performanceHistory??[],blocked=new Set(rawCtx.blockedExerciseIds??[]);
  const eligible=exercises.filter(e=>e.verified!==false&&!blocked.has(e.id)&&equipmentOk(e,have,rawCtx.equipmentExclude??[])&&difficultyOk(e,level)&&ageOk(e,rawCtx.ageBand||"unknown")&&injurySafe(e,{...rawCtx,injuryDataKnown:rawCtx.injuryDataKnown??Boolean(rawCtx.injuries?.length)})&&!(conditionAvoid.length&&hasAny(tags(e),conditionAvoid)));
  if(!eligible.length)throw new NoSafeExerciseError(["equipment","age","level","injury/limitations",...(rules.length?["health conditions"]:[]),"verified exercise library"]);
  const scored=eligible.map(e=>({e,score:scoreExercise(e,{level,goal,track,recentIds,recentMuscles,recentPatterns,weeklyMuscles,weeklyPatterns,seed,history,readiness,aiPreferred:new Set(rawCtx.aiPreferredExerciseIds??[]),blocked})})).filter(x=>Number.isFinite(x.score)).sort((a,b)=>b.score-a.score);
  const stretches=scored.filter(x=>isStretch(x.e)).map(x=>x.e),warmups=scored.filter(x=>isWarmup(x.e)).map(x=>x.e),cores=scored.filter(x=>isCore(x.e)&&!isStretch(x.e)&&!isWarmup(x.e)).map(x=>x.e),outdoors=scored.filter(x=>isOutdoor(x.e)).map(x=>x.e),mainPool=scored.filter(x=>!isStretch(x.e)&&!isWarmup(x.e)&&!isCore(x.e)&&!isOutdoor(x.e)).map(x=>x.e),fallbackMovementPool=scored.filter(x=>!isStretch(x.e)&&!isWarmup(x.e)).map(x=>x.e);
  if(!stretches.length||!warmups.length||!fallbackMovementPool.length){const missing:string[]=[];if(!stretches.length)missing.push("stretching/mobility");if(!warmups.length)missing.push("warm-up");if(!fallbackMovementPool.length)missing.push("main movement");throw new NoSafeExerciseError(missing);}
  const outdoorDay=rawCtx.trainingDays?.length?rawCtx.trainingDays[seed%rawCtx.trainingDays.length]:seed%7;const outdoorForced=Boolean(rawCtx.outdoorTrainingOk)&&(rawCtx.dayOfWeek??date.getDay())===outdoorDay&&outdoors.length>0;
  const count=minutes>=50?5:minutes>=38?4:minutes>=28?3:2;const chosenMain=choose(mainPool.length?mainPool:fallbackMovementPool,count,seed);const chosenCore=cores.length?choose(cores,1,seed+41):[];const moves:SessionMove[]=[];let order=1,total=0;
  const add=(e:ExerciseRow,role:SessionMove["role"],notes?:string)=>{const previous=history.filter(p=>p.exerciseId===e.id).sort((a,b)=>b.date.localeCompare(a.date))[0];const p=prescription(role,level,previous,readiness);moves.push({order:order++,exerciseId:e.id,name:e.name,role,...p,effort:capEffort(p.effort,cap),notes,gif:e.gif,image:e.image});total+=p.estimatedMin??1;};
  const addHydration=()=>{moves.push({order:order++,exerciseId:"hydration-500",name:"Hydration break — drink 500 ml water",role:"hydration",estimatedMin:1,effort:"easy",notes:"Drink 500 ml between workout blocks."});total+=1;};
  add(choose(stretches,1,seed)[0],"stretch","Session opening: mobility/stretching.");add(choose(warmups,1,seed+7)[0],"warmup","Session opening: dynamic warm-up.");
  chosenMain.forEach((e,i)=>{add(e,i===0?"main":"accessory");if(i<chosenMain.length-1)addHydration();});if(outdoorForced){add(outdoors[0],"outdoor","Weekly outdoor rotation; intensity reduced when readiness is low.");addHydration();}if(chosenCore[0])add(chosenCore[0],"core");add(choose(stretches,1,seed+17)[0],"cooldown","Restore mobility and breathing.");
  while(total>minutes+5){const idx=moves.findIndex(m=>m.role==="accessory");if(idx<0)break;total-=moves[idx].estimatedMin??1;moves.splice(idx,1);}moves.forEach((m,i)=>m.order=i+1);
  const missed=rawCtx.missedSessions??0;const adjustment=missed>=2?"Missed-session adjustment: volume held conservative before rebuilding frequency.":missed===1?"Missed-session adjustment: normal volume with conservative progression.":"Progression uses recent completion and effort.";
  return{sessionId:`sess_${rawCtx.userId.slice(0,8)}_${dateKey}_${seed.toString(16).slice(0,6)}`,userId:rawCtx.userId,dateKey,createdAt:new Date().toISOString(),estimatedMinutes:total,moves,outdoor:outdoorForced,hydrationRemindersMl:moves.filter(m=>m.role==="hydration").map(()=>500),postWorkoutFoodHint:"After training: hydrate and choose a balanced protein + carbohydrate meal from Nutrition.",meta:{usedDefaults,candidateCount:eligible.length,outdoorForced,dataQuality:usedDefaults.length?"partial":"complete",status:"ready",version:2,adjustment,readiness,missedSessions:missed,selectionPolicy:"database→safety→load/fatigue→progression→AI preference→deterministic rotation",healthNotes} as any};
}
